### ISSUE TITLE
will there be no sources =( ?

### ISSUE THREAD

**Issue by DeAlexPesh** [nov30th/s1-mini-computer-tft-screen-release#1]
...

**Comment by nov30th** [comment]
Currently there is no plan to open source mainly because the acemagin offical seller where I bought from refuese to provider any info about the screen.
Just as my private project.
I may open source after I got my home asssitant connects with and it runs smooth.

**Comment by alycecil** [comment]
its not just not open source it uses key and auth to lock down even changing the image files. kinda in the wtf are you doing bro realm

**Comment by nov30th** [comment]
> its not just not open source it uses key and auth to lock down even changing the image files. kinda in the wtf are you doing bro realm

I've post the reason in forum, if you don't like wut I made as currently my private proj, there is someone open the data struct for TFT you can just simple make one. Again, I just released the half-done proj for testing or someone willing to use. NOT A COMPLETED PROJECT.

**Comment by geduxas** [comment]
> Currently there is no plan to open source mainly because the acemagin offical seller where I bought from refuese to provider any info about the screen. Just as my private project. I may open source after I got my home asssitant connects with and it runs smooth.

it's just nextion LCD screen with serial comunication, whats so important about that ? Or i am missing something?

**Comment by nov30th** [comment]
> > Currently there is no plan to open source mainly because the acemagin offical seller where I bought from refuese to provider any info about the screen. Just as my private project. I may open source after I got my home asssitant connects with and it runs smooth.
> 
> it's just nextion LCD screen with serial comunication, whats so important about that ? Or i am missing something?

then you can just simply makes one. I admit I am wrong which shared my private binary files for you, sorry.

**Comment by geduxas** [comment]
@nov30th you told that seller is not sharing any information about screen.. and for now I don't have access to that model, just sniffing around, and screen looks to me as simple nextion products.. i am wrong?

**Comment by nov30th** [comment]
@geduxas what's your question? This is my screen control in linux project.

**Comment by geduxas** [comment]
Trying to understand why it's so secret project :D

**Comment by nov30th** [comment]
just because I did a lot of research on the data on my own and and finsihed the testing version which is just "can run" not a "project" and I only open source for completed project.

**Comment by nov30th** [comment]
but as I am busy on work so I believe someone need this, just shared the binary files for use. otherwise I may share nothing if too many ppl complain

**Comment by NilzOS** [comment]
I switched to [This Project](https://github.com/tjaworski/AceMagic-S1-LED-TFT-Linux/tree/main/s1panel)
It looks more promising and I hate binary releases.

**Comment by nov30th** [comment]
@NilzOS the project you mentioned has been wrote into README file.
